FROM node:13.12.0-alpine
WORKDIR /app
EXPOSE 3000
COPY . ./
WORKDIR /app/frontend
ENV PATH /app/frontend/node_modules/.bin:$PATH
RUN npm install --silent
RUN npm install --save bootstrap@4.1.3 react-cookie@3.0.4 react-router-dom@4.3.1 reactstrap@6.5.0 react-alert
CMD ["npm", "start"]